export const dietitians = [
    {
      id: 1,
      name: 'Başak Suna Albayrak',
      namelink: 'basak-suna-albayrak',
      online: true,
      title: 'Uzman Diyetisyen',
      sessions: 17,
      rating: 4,
      language: 'TR | EN',
      specialties: [
        { name: 'Kilo Alma', speciallink: 'kilo-alma' },
        { name: 'Kilo Verme', speciallink: 'kilo-verme' },
        { name: 'Kilo Kontrolü', speciallink: 'kilo-kontrolu' },
        { name: 'Çocukluk ve Ergenlikte Beslenme', speciallink: 'cocukluk-ve-ergenlikte-beslenme' },
        { name: 'Kurumsal Beslenme Danışmanlığı', speciallink: 'kurumsal-beslenme-danismanligi' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 395,
      minSessionAmount: 395,
    },
    {
      id: 2,
      name: 'Sosin Yakacı',
      namelink: 'sosin-yakaci',
      online: true,
      title: 'Diyetisyen',
      sessions: 8,
      rating: 2,
      language: 'TR | EN',
      specialties: [
        { name: 'Kilo Verme', speciallink: 'kilo-verme' },
        { name: 'Obezite', speciallink: 'obezite' },
        { name: 'Hamilelik ve Doğum Sonrası Beslenme', speciallink: 'hamilelik-ve-dogum-sonrasi-beslenme' },
        { name: 'İnsülin Direncinde Beslenme', speciallink: 'insulin-direncinde-beslenme' },
        { name: 'Kolesterol ve Beslenme', speciallink: 'kolesterol-ve-beslenme' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 270,
      minSessionAmount: 270,
    },
    {
      id: 3,
      name: 'Tunahan Berber',
      namelink: 'tunahan-berber',
      online: false,
      title: 'Diyetisyen',
      sessions: 0,
      rating: 1,
      specialties: [
        { name: 'Kilo Verme', speciallink: 'kilo-verme' },
        { name: 'Kilo Alma', speciallink: 'kilo-alma' },
        { name: 'Kilo Kontrolü', speciallink: 'kilo-kontrolu' },
        { name: 'Obezite', speciallink: 'obezite' },
        { name: 'Sporcu Beslenmesi', speciallink: 'sporcu-beslenmesi' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 395,
      minSessionAmount: 395,
    },
    {
      id: 4,
      name: 'Güldane Coşkun',
      namelink: 'guldane-coskun',
      online: true,
      title: 'Diyetisyen',
      sessions: 1,
      rating: 1,
      language: 'TR',
      specialties: [
        { name: 'Obezite', speciallink: 'obezite' },
        { name: 'Kilo Kontrolü', speciallink: 'kilo-kontrolu' },
        { name: 'Diyabet (Şeker) Hastalığında Beslenme', speciallink: 'diyabet-seker-hastaliginda-beslenme' },
        { name: 'Hamilelik ve Doğum Sonrası Beslenme', speciallink: 'hamilelik-ve-dogum-sonrasi-beslenme' },
        { name: 'Çocukluk ve Ergenlikte Beslenme', speciallink: 'cocukluk-ve-ergenlikte-beslenme' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 270,
      minSessionAmount: 270,
    },
    {
      id: 5,
      name: 'Melike Özkan',
      namelink: 'melike-ozkan',
      online: true,
      title: 'Diyetisyen',
      sessions: 0,
      rating: 0,
      language: 'TR | EN',
      specialties: [
        { name: 'Kilo Verme', speciallink: 'kilo-verme' },
        { name: 'Obezite', speciallink: 'obezite' },
        { name: 'Aralıklı Oruç', speciallink: 'aralikli-oruc' },
        { name: 'Ketojenik Beslenme', speciallink: 'ketojenik-beslenme' },
        { name: 'Yeme Bozuklukları', speciallink: 'yeme-bozukluklari' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 270,
      minSessionAmount: 270,
    },
    {
      id: 6,
      name: 'Nurseda Seyhan',
      namelink: 'nurseda-seyhan',
      online: true,
      title: 'Diyetisyen',
      sessions: 2,
      rating: 0,
      language: 'TR | EN',
      specialties: [
        { name: 'Kilo Verme', speciallink: 'kilo-verme' },
        { name: 'Diğer Hastalıklar', speciallink: 'diger-hastaliklar' },
        { name: 'Yeme Bozuklukları', speciallink: 'yeme-bozukluklari' },
        { name: 'Hamilelik ve Doğum Sonrası Beslenme', speciallink: 'hamilelik-ve-dogum-sonrasi-beslenme' },
        { name: 'Çocukluk ve Ergenlikte Beslenme', speciallink: 'cocukluk-ve-ergenlikte-beslenme' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 270,
      minSessionAmount: 270,
    },
    {
      id: 7,
      name: 'Sabiha Ece Butakın',
      namelink: 'sabiha-ece-butakin',
      online: true,
      title: 'Diyetisyen',
      sessions: 1,
      rating: 0,
      language: 'TR',
      specialties: [
        { name: 'Çocukluk ve Ergenlikte Beslenme', speciallink: 'cocukluk-ve-ergenlikte-beslenme' },
        { name: 'Kilo Alma', speciallink: 'kilo-alma' },
        { name: 'Kilo Verme', speciallink: 'kilo-verme' },
        { name: 'Sporcu Beslenmesi', speciallink: 'sporcu-beslenmesi' },
        { name: 'İnsülin Direncinde Beslenme', speciallink: 'insulin-direncinde-beslenme' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 270,
      minSessionAmount: 270,
    },
    {
      id: 8,
      name: 'Büşra Boyalı Özbey',
      namelink: 'busra-boyalı-ozbey',
      online: true,
      title: 'Diyetisyen',
      sessions: 193,
      rating: 201,
      language: 'TR',
      specialties: [
        { name: 'Hamilelik ve Doğum Sonrası Beslenme', speciallink: 'hamilelik-ve-dogum-sonrasi-beslenme' },
        { name: 'Çocukluk ve Ergenlikte Beslenme', speciallink: 'cocukluk-ve-ergenlikte-beslenme' },
        { name: 'Kilo Verme', speciallink: 'kilo-verme' },
        { name: 'Kilo Alma', speciallink: 'kilo-alma' },
        { name: 'Diğer Hastalıklar', speciallink: 'diger-hastaliklar' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 270,
      minSessionAmount: 270,
    },
    {
      id: 9,
      name: 'Melis Büyükgebiz',
      namelink: 'melis-buyukgebiz',
      online: true,
      title: 'Diyetisyen',
      sessions: 42,
      rating: 40,
      language: 'TR',
      specialties: [
        { name: 'Kilo Verme', speciallink: 'kilo-verme' },
        { name: 'Aralıklı Oruç', speciallink: 'aralikli-oruc' },
        { name: 'Diğer Hastalıklar', speciallink: 'diger-hastaliklar' },
        { name: 'Çocukluk ve Ergenlikte Beslenme', speciallink: 'cocukluk-ve-ergenlikte-beslenme' },
        { name: 'Obezite', speciallink: 'obezite' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 270,
      minSessionAmount: 270,
    },
    {
      id: 10,
      name: 'Betül Şahin Yılmaz',
      namelink: 'betul-sahin-yilmaz',
      online: true,
      title: 'Diyetisyen',
      sessions: 10,
      rating: 10,
      language: 'TR',
      specialties: [
        { name: 'Kilo Verme', speciallink: 'kilo-verme' },
        { name: 'Hamilelik ve Doğum Sonrası Beslenme', speciallink: 'hamilelik-ve-dogum-sonrasi-beslenme' },
        { name: 'Çocukluk ve Ergenlikte Beslenme', speciallink: 'cocukluk-ve-ergenlikte-beslenme' },
        { name: 'Kalp ve Damar Hastalıklarında Beslenme', speciallink: 'kalp-ve-damar-hastaliklarinda-beslenme' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 270,
      minSessionAmount: 270,
    },
  ];
  