export const fitnessTrainers = [
    {
      id: 1,
      name: 'Yavuz İhsan Kılıç',
      namelink: 'yavuz-ihsan-kilic',
      online: true,
      title: 'Fitness Eğitmeni',
      sessions: 12,
      rating: 0,
      language: 'TR',
      specialties: [
        { name: 'Fonksiyonel Antrenman', speciallink: 'fonksiyonel-antrenman' },
        { name: 'Atletik Performans', speciallink: 'atletik-performans' },
        { name: 'Düzeltici Egzersizler', speciallink: 'duzeltici-egzersizler' },
        { name: 'Medikal Fitness', speciallink: 'medikal-fitness' },
        { name: 'Metabolik Antrenman', speciallink: 'metabolik-antrenman' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 245,
      minSessionAmount: 245,
    },
    {
      id: 2,
      name: 'Buse Vardarol',
      namelink: 'buse-vardarol',
      online: true,
      title: 'Fitness Eğitmeni',
      sessions: 1,
      rating: 0,
      language: 'TR | EN',
      specialties: [
        { name: 'Fonksiyonel Antrenman', speciallink: 'fonksiyonel-antrenman' },
        { name: 'Düzeltici Egzersizler', speciallink: 'duzeltici-egzersizler' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 245,
      minSessionAmount: 245,
    },
    {
      id: 3,
      name: 'İrfan Yüncü',
      namelink: 'irfan-yuncu',
      online: false,
      title: 'Fitness Eğitmeni',
      sessions: 0,
      rating: 0,
      language: 'TR',
      specialties: [
        { name: 'Fonksiyonel Antrenman', speciallink: 'fonksiyonel-antrenman' },
        { name: 'Atletik Performans', speciallink: 'atletik-performans' },
        { name: 'Medikal Fitness', speciallink: 'medikal-fitness' },
        { name: 'Düzeltici Egzersizler', speciallink: 'duzeltici-egzersizler' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 245,
      minSessionAmount: 245,
    },
    {
      id: 4,
      name: 'Mert Öztürk',
      namelink: 'mert-ozturk',
      online: false,
      title: 'Fitness Eğitmeni',
      sessions: 0,
      rating: 0,
      language: 'TR',
      specialties: [
        { name: 'Fonksiyonel Antrenman', speciallink: 'fonksiyonel-antrenman' },
        { name: 'Atletik Performans', speciallink: 'atletik-performans' },
        { name: 'Medikal Fitness', speciallink: 'medikal-fitness' },
        { name: 'Düzeltici Egzersizler', speciallink: 'duzeltici-egzersizler' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 245,
      minSessionAmount: 245,
    },
    {
      id: 5,
      name: 'Berkant Bayazıt',
      namelink: 'berkant-bayazit',
      online: false,
      title: 'Fitness Eğitmeni',
      sessions: 0,
      rating: 0,
      language: 'TR',
      specialties: [
        { name: 'Düzeltici Egzersizler', speciallink: 'duzeltici-egzersizler' },
        { name: 'Fonksiyonel Antrenman', speciallink: 'fonksiyonel-antrenman' },
        { name: 'Atletik Performans', speciallink: 'atletik-performans' },
        { name: 'Medikal Fitness', speciallink: 'medikal-fitness' },
        { name: 'Mobilite', speciallink: 'mobilite' },
      ],
      certifications: ['Eğitim ve Sertifikaları Gör'],
      fee: 245,
      minSessionAmount: 245,
    },
  ];
  