export const  psychologists= [
    {
        id: 1,
        name: 'Gül Çolak',
        namelink: 'gul-colak',
        online: true,
        title: 'Uzman Klinik Psikolog',
        sessions: 73,
        rating: 0,
        language: 'TR',
        specialties: [
          { name: 'Uyku Bozuklukları', speciallink: 'uyku-bozukluklari' },
          { name: 'Depresyon', speciallink: 'depresyon' },
          { name: 'Panik Bozukluk', speciallink: 'panik-bozukluk' },
          { name: 'Obsesif Kompulsif Bozukluk', speciallink: 'obsesif-kompulsif-bozukluk' },
          { name: 'Ergenlik Çağı Sorunları', speciallink: 'ergenlik-cagi-sorunlari' },
        ],
        certifications: ['Eğitim ve Sertifikaları Gör'],
        fee: 320,
        minSessionAmount: 320,
      },
      {
        id: 2,
        name: 'Hamza Say',
        namelink: 'hamza-say',
        online: true,
        title: 'Uzman Klinik Psikolog',
        sessions: 19,
        rating: 1,
        language: 'TR',
        specialties: [
          { name: 'Bireysel Terapi', speciallink: 'bireysel-terapi' },
          { name: 'Ebeveyn Danışmanlığı', speciallink: 'ebeveyn-danismanligi' },
          { name: 'Obsesif Kompulsif Bozukluk', speciallink: 'obsesif-kompulsif-bozukluk' },
          { name: 'Depresyon', speciallink: 'depresyon' },
          { name: 'Cinsel İşlev Bozuklukları', speciallink: 'cinsel-islev-bozukluklari' },
        ],
        certifications: ['Eğitim ve Sertifikaları Gör'],
        fee: 320,
        minSessionAmount: 320,
      },
      {
        id: 3,
        name: 'Çağla Demirel',
        namelink: 'cagla-demirel',
        online: true,
        title: 'Psikolog | Aile Danışmanı',
        sessions: 382,
        rating: 93,
        language: 'TR | EN',
        specialties: [
          { name: 'Yeme Bozuklukları', speciallink: 'yeme-bozukluklari' },
          { name: 'Depresyon', speciallink: 'depresyon' },
          { name: 'Travma Sonrası Stres Bozukluğu', speciallink: 'travma-sonrasi-stres-bozuklugu' },
          { name: 'Kişilik Bozuklukları', speciallink: 'kisilik-bozukluklari' },
          { name: 'İş ve Çalışan Psikolojisi', speciallink: 'is-ve-calisans-psikolojisi' },
        ],
        certifications: ['Eğitim ve Sertifikaları Gör'],
        fee: 370,
        minSessionAmount: 370,
      },
      {
        id: 4,
        name: 'Nur Destioğlu',
        namelink: 'nur-destioglu',
        online: true,
        title: 'Psikolog | Aile Danışmanı',
        sessions: 59,
        rating: 6,
        language: 'TR',
        specialties: [
          { name: 'Depresyon', speciallink: 'depresyon' },
          { name: 'Kaygı (Anksiyete)', speciallink: 'kaygi-anksiyete' },
          { name: 'İlişki Sorunları', speciallink: 'iliski-sorunlari' },
          { name: 'Obsesif Kompulsif Bozukluk', speciallink: 'obsesif-kompulsif-bozukluk' },
          { name: 'Fobiler', speciallink: 'fobiler' },
        ],
        certifications: ['Eğitim ve Sertifikaları Gör'],
        fee: 320,
        minSessionAmount: 320,
      },
      {
        id: 5,
        name: 'Nilüfer Şişman',
        namelink: 'nilufer-sisman',
        online: true,
        title: 'Uzman Klinik Psikolog',
        sessions: 10,
        rating: 0,
        specialties: [
          { name: 'Bireysel Terapi', speciallink: 'bireysel-terapi' },
          { name: 'Çocukluk Çağı Sorunları', speciallink: 'cocukluk-cagi-sorunlari' },
          { name: 'Ergenlik Çağı Sorunları', speciallink: 'ergenlik-cagi-sorunlari' },
        ],
        certifications: ['Eğitim ve Sertifikaları Gör'],
        fee: 370,
        minSessionAmount: 370,
      },
      {
        id: 6,
        name: 'Mert Berber',
        namelink: 'mert-berber',
        online: true,
        title: 'Uzman Klinik Psikolog',
        sessions: 90,
        rating: 2,
        language: 'TR | EN',
        specialties: [
          { name: 'Depresyon', speciallink: 'depresyon' },
          { name: 'Kaygı (Anksiyete)', speciallink: 'kaygi-anksiyete' },
          { name: 'Duygu Durum Bozuklukları', speciallink: 'duygu-durum-bozukluklari' },
          { name: 'Fobiler', speciallink: 'fobiler' },
          { name: 'Obsesif Kompulsif Bozukluk', speciallink: 'obsesif-kompulsif-bozukluk' },
        ],
        certifications: ['Eğitim ve Sertifikaları Gör'],
        fee: 320,
        minSessionAmount: 320,
      },
      {
        id: 7,
        name: 'Tuba Ulusan',
        namelink: 'tuba-ulusan',
        online: false,
        title: 'Uzman Klinik Psikolog',
        sessions: 2204,
        rating: 43,
        language: 'TR',
        specialties: [
          { name: 'Travma Sonrası Stres Bozukluğu', speciallink: 'travma-sonrasi-stres-bozuklugu' },
          { name: 'Kaygı (Anksiyete)', speciallink: 'kaygi-anksiyete' },
          { name: 'Fobiler', speciallink: 'fobiler' },
          { name: 'İlişki Sorunları', speciallink: 'iliski-sorunlari' },
          { name: 'Takıntılar (Obsesif Kompülsif Bozukluk)', speciallink: 'takintilar-obsesif-kompulsif-bozukluk' },
        ],
        certifications: ['Eğitim ve Sertifikaları Gör'],
        fee: 420,
        minSessionAmount: 420,
      },
      {
        id: 8,
        name: 'Çağan Yüksel',
        namelink: 'cagan-yuksel',
        online: false,
        title: 'Uzman Klinik Psikolog',
        sessions: 876,
        rating: 36,
        language: 'TR | EN',
        specialties: [
          { name: 'Cinsel İşlev Bozuklukları', speciallink: 'cinsel-islev-bozukluklari' },
          { name: 'Panik Bozukluk', speciallink: 'panik-bozukluk' },
          { name: 'Takıntılar (Obsesif Kompülsif Bozukluk)', speciallink: 'takintilar-obsesif-kompulsif-bozukluk' },
          { name: 'Depresyon', speciallink: 'depresyon' },
          { name: 'Kaygı (Anksiyete)', speciallink: 'kaygi-anksiyete' },
        ],
        certifications: ['Eğitim ve Sertifikaları Gör'],
        fee: 420,
        minSessionAmount: 420,
      }
    ];
    
    export default psychologists;